name = "your-existing-project-worker" # Give your Worker a unique name
main = "src/index.ts"                # Point this to your main Worker file (e.g., src/index.ts or dist/index.js)
compatibility_date = "2025-05-24"     # Use today's date or a recent date

# D1 Binding
# You'll need to create your D1 database first using `wrangler d1 create my_app_db`
# Then, get the database_id from the output or the Cloudflare dashboard.
[[d1_databases]]
binding = "DB" # This is the name you'll use in your Worker code (c.env.DB)
database_name = "my_app_db" # The name you chose for your D1 database
database_id = "YOUR_D1_DATABASE_ID" # e.g., "b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"

# KV Namespace Binding
# You'll need to create your KV namespace first using `wrangler kv:namespace create my_app_kv`
# Then, get the id from the output.
[[kv_namespaces]]
binding = "main"
id = "8f1a68deb05e4474ae9835460dfa87de"

# R2 Bucket Binding
# You'll need to create your R2 bucket first using `wrangler r2 bucket create my-app-r2-bucket`
[[r2_buckets]]
binding = "MY_R2_BUCKET" # This is the name you'll use in your Worker code (c.env.MY_R2_BUCKET)
bucket_name = "rag"

# Durable Object Binding
# The `class_name` must match the name of your Durable Object class exported from your Worker.
[[durable_objects.bindings]]
name = "MY_DO" # This is the name you'll use in your Worker code (c.env.MY_DO)
class_name = "MyDurableObject" # The name of your Durable Object class (e.g., in src/index.ts)

# Vectorize Index Binding
# You'll need to create your Vectorize index first using `wrangler vectorize create my_app_vector_index --dimensions 1536 --metric DOT_PRODUCT`
[[vectorize.bindings]]
name = "MY_VECTOR_INDEX" # This is the name you'll use in your Worker code (c.env.MY_VECTOR_INDEX)
index_name = "my_app_vector_index" # The name you chose for your Vectorize index

# --- Optional: Add other bindings if you need them ---
# Queues:
# [[queues.producers]]
# binding = "MY_QUEUE_PRODUCER"
# queue = "my-app-queue"

# [[queues.consumers]]
# queue = "my-app-queue"
# script = "src/index" # Point to your Worker entry file
# handler = "queueHandler" # An exported function in your worker for handling queue messages

# Hyperdrive:
# [[hyperdrive]]
# binding = "MY_HYPERDRIVE"
# id = "YOUR_HYPERDRIVE_ID"

# Environment variables for production
# [vars]
# MY_API_KEY = "super-secret-key"

# Environment variables for local development (not committed to git)
# [dev.vars]
# MY_DEV_API_KEY = "dev-secret-key"

# Local Development Settings (Miniflare)
# [dev]
# ip = "0.0.0.0" # Listen on all IPs
# port = 8787   # Default port for wrangler dev