/**
 * Model registry with default model settings
 */
import { ModelSettings, ModelProvider, ModelCategory, ModelCapabilities } from "@/types/model-settings";

/**
 * Default model capabilities
 */
const DEFAULT_VISION_FUNCTION_CAPABILITIES: ModelCapabilities = {
  text: true,
  vision: true,
  audio: false,
  video: false,
  functions: true,
  streaming: true,
  json_mode: true,
  fine_tuning: false,
  thinking: false,
  search_grounding: false,
  code_execution: false,
  structured_output: true,
  image_generation: false,
  video_generation: false,
  audio_generation: false
};

/**
 * Google AI model settings
 */
export const GOOGLE_MODELS: Record<string, Partial<ModelSettings>> = {
  // Gemini 2.5 Models
  "models/gemini-2.5-pro-preview-05-06": {
    name: "Gemini 2.5 Pro",
    provider: "google",
    model_id: "models/gemini-2.5-pro-preview-05-06",
    max_tokens: 65536,
    input_cost_per_token: 0.00001,
    output_cost_per_token: 0.00003,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 1048576,
    description: "Google's most capable multimodal model with advanced reasoning",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: true,
      video: true,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: true,
      search_grounding: true,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "models/gemini-2.5-flash-preview-04-17": {
    name: "Gemini 2.5 Flash",
    provider: "google",
    model_id: "models/gemini-2.5-flash-preview-04-17",
    max_tokens: 65536,
    input_cost_per_token: 0.000003,
    output_cost_per_token: 0.000005,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 1048576,
    description: "Fast and efficient multimodal model with long context",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: true,
      video: true,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: true,
      search_grounding: true,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  // Gemini 2.0 Models
  "models/gemini-2.0-pro": {
    name: "Gemini 2.0 Pro",
    provider: "google",
    model_id: "models/gemini-2.0-pro",
    max_tokens: 8192,
    input_cost_per_token: 0.000007,
    output_cost_per_token: 0.00002,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 32768,
    description: "Balanced model for text, vision, and function calling",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: true,
      video: true,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: true,
      search_grounding: true,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "models/gemini-2.0-flash": {
    name: "Gemini 2.0 Flash",
    provider: "google",
    model_id: "models/gemini-2.0-flash",
    max_tokens: 8192,
    input_cost_per_token: 0.000003,
    output_cost_per_token: 0.000005,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 32768,
    description: "Fast and efficient multimodal model",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: true,
      video: true,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: true,
      search_grounding: true,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "models/gemini-2.0-flash-live-001": {
    name: "Gemini 2.0 Flash Live",
    provider: "google",
    model_id: "models/gemini-2.0-flash-live-001",
    max_tokens: 8192,
    input_cost_per_token: 0.000003,
    output_cost_per_token: 0.000005,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 1048576,
    description: "Real-time interactive model with audio output",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: true,
      video: true,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: false,
      search_grounding: true,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: true
    },
  },
  // Gemini 1.5 Models
  "models/gemini-1.5-pro": {
    name: "Gemini 1.5 Pro",
    provider: "google",
    model_id: "models/gemini-1.5-pro",
    max_tokens: 65536,
    input_cost_per_token: 0.00001,
    output_cost_per_token: 0.00003,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 1048576,
    description: "Google's capable multimodal model for text, vision, and function calling",
    category: "multimodal",
    capabilities: DEFAULT_VISION_FUNCTION_CAPABILITIES,
  },
  "models/gemini-1.5-flash": {
    name: "Gemini 1.5 Flash",
    provider: "google",
    model_id: "models/gemini-1.5-flash",
    max_tokens: 65536,
    input_cost_per_token: 0.000003,
    output_cost_per_token: 0.000005,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 1048576,
    description: "Efficient multimodal model for text, vision, and function calling",
    category: "multimodal",
    capabilities: DEFAULT_VISION_FUNCTION_CAPABILITIES,
  },
  // Image Generation Models
  "models/imagen-3.0-generate-002": {
    name: "Imagen 3",
    provider: "google",
    model_id: "models/imagen-3.0-generate-002",
    max_tokens: 4096,
    input_cost_per_token: 0.0001,
    output_cost_per_token: 0.0001,
    supports_vision: false,
    supports_functions: false,
    supports_streaming: false,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 4096,
    description: "High-quality text-to-image generation model",
    category: "image",
    capabilities: {
      text: false,
      vision: false,
      audio: false,
      video: false,
      functions: false,
      streaming: false,
      json_mode: false,
      fine_tuning: false,
      thinking: false,
      search_grounding: false,
      code_execution: false,
      structured_output: false,
      image_generation: true,
      video_generation: false,
      audio_generation: false
    },
  },
  // Video Generation Models
  "models/veo-2.0-generate-001": {
    name: "Veo 2",
    provider: "google",
    model_id: "models/veo-2.0-generate-001",
    max_tokens: 4096,
    input_cost_per_token: 0.0001,
    output_cost_per_token: 0.0001,
    supports_vision: true,
    supports_functions: false,
    supports_streaming: false,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 4096,
    description: "High-quality text-to-video and image-to-video generation model",
    category: "multimodal",
    capabilities: {
      text: false,
      vision: true,
      audio: false,
      video: false,
      functions: false,
      streaming: false,
      json_mode: false,
      fine_tuning: false,
      thinking: false,
      search_grounding: false,
      code_execution: false,
      structured_output: false,
      image_generation: false,
      video_generation: true,
      audio_generation: false
    },
  },
  // Embedding Models
  "models/gemini-embedding-exp-03-07": {
    name: "Gemini Embedding",
    provider: "google",
    model_id: "models/gemini-embedding-exp-03-07",
    max_tokens: 8192,
    input_cost_per_token: 0.0000002,
    output_cost_per_token: 0.0000002,
    supports_vision: false,
    supports_functions: false,
    supports_streaming: false,
    default_temperature: 0.0,
    default_top_p: 1.0,
    context_window: 8192,
    description: "State-of-the-art text embedding model",
    category: "embedding",
    capabilities: {
      text: true,
      vision: false,
      audio: false,
      video: false,
      functions: false,
      streaming: false,
      json_mode: false,
      fine_tuning: false,
      thinking: false,
      search_grounding: false,
      code_execution: false,
      structured_output: false,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "models/text-embedding-004": {
    name: "Text Embedding",
    provider: "google",
    model_id: "models/text-embedding-004",
    max_tokens: 2048,
    input_cost_per_token: 0.0000001,
    output_cost_per_token: 0.0000001,
    supports_vision: false,
    supports_functions: false,
    supports_streaming: false,
    default_temperature: 0.0,
    default_top_p: 1.0,
    context_window: 2048,
    description: "Efficient text embedding model",
    category: "embedding",
    capabilities: {
      text: true,
      vision: false,
      audio: false,
      video: false,
      functions: false,
      streaming: false,
      json_mode: false,
      fine_tuning: false,
      thinking: false,
      search_grounding: false,
      code_execution: false,
      structured_output: false,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
};

/**
 * OpenAI model settings
 */
export const OPENAI_MODELS: Record<string, Partial<ModelSettings>> = {
  // GPT-4.1 Models
  "gpt-4.1": {
    name: "GPT-4.1",
    provider: "openai",
    model_id: "gpt-4.1",
    max_tokens: 32768,
    input_cost_per_token: 0.000002,
    output_cost_per_token: 0.000008,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 1047576,
    description: "OpenAI's flagship model for complex tasks with problem solving across domains",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: true,
      thinking: false,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "gpt-4.1-mini": {
    name: "GPT-4.1 mini",
    provider: "openai",
    model_id: "gpt-4.1-mini",
    max_tokens: 32768,
    input_cost_per_token: 0.0000004,
    output_cost_per_token: 0.0000016,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 1047576,
    description: "Balanced model for intelligence, speed, and cost",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: true,
      thinking: false,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  // O-Series Models
  "o4-mini": {
    name: "o4-mini",
    provider: "openai",
    model_id: "o4-mini",
    max_tokens: 100000,
    input_cost_per_token: 0.0000011,
    output_cost_per_token: 0.0000044,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 200000,
    description: "Fast, affordable reasoning model optimized for coding and visual tasks",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: true,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "o3": {
    name: "o3",
    provider: "openai",
    model_id: "o3",
    max_tokens: 100000,
    input_cost_per_token: 0.00001,
    output_cost_per_token: 0.00004,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 200000,
    description: "OpenAI's most powerful reasoning model for math, science, coding, and visual reasoning",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: true,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "o3-mini": {
    name: "o3-mini",
    provider: "openai",
    model_id: "o3-mini",
    max_tokens: 100000,
    input_cost_per_token: 0.0000011,
    output_cost_per_token: 0.0000044,
    supports_vision: false,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 200000,
    description: "Small reasoning model with high intelligence at affordable cost",
    category: "text",
    capabilities: {
      text: true,
      vision: false,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: true,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  // GPT-4o Models
  "gpt-4o-2024-05-13": {
    name: "GPT-4o (May 2024)",
    provider: "openai",
    model_id: "gpt-4o-2024-05-13",
    max_tokens: 16384,
    input_cost_per_token: 0.0000025,
    output_cost_per_token: 0.00001,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 128000,
    description: "OpenAI's latest multimodal model with improved capabilities",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: true,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: true,
      thinking: false,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "gpt-4o": {
    name: "GPT-4o",
    provider: "openai",
    model_id: "gpt-4o",
    max_tokens: 16384,
    input_cost_per_token: 0.0000025,
    output_cost_per_token: 0.00001,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 128000,
    description: "OpenAI's versatile, high-intelligence flagship model",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: true,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: true,
      thinking: false,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "gpt-4o-mini": {
    name: "GPT-4o mini",
    provider: "openai",
    model_id: "gpt-4o-mini",
    max_tokens: 16384,
    input_cost_per_token: 0.00000015,
    output_cost_per_token: 0.0000006,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 128000,
    description: "Fast, affordable small model for focused tasks",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: true,
      thinking: false,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "chatgpt-4o-latest": {
    name: "ChatGPT-4o",
    provider: "openai",
    model_id: "chatgpt-4o-latest",
    max_tokens: 16384,
    input_cost_per_token: 0.000005,
    output_cost_per_token: 0.000015,
    supports_vision: true,
    supports_functions: false,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 128000,
    description: "GPT-4o model used in ChatGPT",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: false,
      video: false,
      functions: false,
      streaming: true,
      json_mode: false,
      fine_tuning: false,
      thinking: false,
      search_grounding: false,
      code_execution: false,
      structured_output: false,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  // Legacy Models
  "gpt-4-turbo": {
    name: "GPT-4 Turbo",
    provider: "openai",
    model_id: "gpt-4-turbo",
    max_tokens: 4096,
    input_cost_per_token: 0.00001,
    output_cost_per_token: 0.00003,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 128000,
    description: "Optimized version of GPT-4 with vision capabilities",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: false,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "gpt-4": {
    name: "GPT-4",
    provider: "openai",
    model_id: "gpt-4",
    max_tokens: 8192,
    input_cost_per_token: 0.00003,
    output_cost_per_token: 0.00006,
    supports_vision: false,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 8192,
    description: "OpenAI's powerful large language model",
    category: "text",
    capabilities: {
      text: true,
      vision: false,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: false,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "gpt-3.5-turbo": {
    name: "GPT-3.5 Turbo",
    provider: "openai",
    model_id: "gpt-3.5-turbo",
    max_tokens: 4096,
    input_cost_per_token: 0.0000015,
    output_cost_per_token: 0.000002,
    supports_vision: false,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 16385,
    description: "Efficient model for most text generation tasks",
    category: "text",
    capabilities: {
      text: true,
      vision: false,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: false,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  // Image Generation Models
  "dall-e-3": {
    name: "DALL-E 3",
    provider: "openai",
    model_id: "dall-e-3",
    max_tokens: 4096,
    input_cost_per_token: 0.02,
    output_cost_per_token: 0.02,
    supports_vision: false,
    supports_functions: false,
    supports_streaming: false,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 4096,
    description: "OpenAI's advanced text-to-image generation model",
    category: "image",
    capabilities: {
      text: false,
      vision: false,
      audio: false,
      video: false,
      functions: false,
      streaming: false,
      json_mode: false,
      fine_tuning: false,
      thinking: false,
      search_grounding: false,
      code_execution: false,
      structured_output: false,
      image_generation: true,
      video_generation: false,
      audio_generation: false
    },
  },
};

/**
 * Anthropic model settings
 */
export const ANTHROPIC_MODELS: Record<string, Partial<ModelSettings>> = {
  "claude-3-5-sonnet": {
    name: "Claude 3.5 Sonnet",
    provider: "anthropic",
    model_id: "claude-3-5-sonnet-20240620",
    max_tokens: 4096,
    input_cost_per_token: 0.000003,
    output_cost_per_token: 0.000015,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 200000,
    description: "Anthropic's latest and most capable multimodal model",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: true,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "claude-3-opus": {
    name: "Claude 3 Opus",
    provider: "anthropic",
    model_id: "claude-3-opus-20240229",
    max_tokens: 4096,
    input_cost_per_token: 0.00001,
    output_cost_per_token: 0.00003,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 200000,
    description: "Anthropic's most powerful multimodal model",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: true,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "claude-3-sonnet": {
    name: "Claude 3 Sonnet",
    provider: "anthropic",
    model_id: "claude-3-sonnet-20240229",
    max_tokens: 4096,
    input_cost_per_token: 0.000003,
    output_cost_per_token: 0.000015,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 200000,
    description: "Balanced multimodal model for most tasks",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: true,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
  "claude-3-haiku": {
    name: "Claude 3 Haiku",
    provider: "anthropic",
    model_id: "claude-3-haiku-20240307",
    max_tokens: 4096,
    input_cost_per_token: 0.00000025,
    output_cost_per_token: 0.00000125,
    supports_vision: true,
    supports_functions: true,
    supports_streaming: true,
    default_temperature: 0.7,
    default_top_p: 1.0,
    context_window: 200000,
    description: "Fast and efficient multimodal model",
    category: "multimodal",
    capabilities: {
      text: true,
      vision: true,
      audio: false,
      video: false,
      functions: true,
      streaming: true,
      json_mode: true,
      fine_tuning: false,
      thinking: true,
      search_grounding: false,
      code_execution: true,
      structured_output: true,
      image_generation: false,
      video_generation: false,
      audio_generation: false
    },
  },
};

/**
 * All model settings by provider
 */
export const MODEL_REGISTRY = {
  google: GOOGLE_MODELS,
  openai: OPENAI_MODELS,
  anthropic: ANTHROPIC_MODELS,
};
