name: Generate Code Structure Graph
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate dependency graph (madge)
        run: pnpm madge --image graph.svg src/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-structure-graph
          path: graph.svg
